# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\AuthorDetailWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 672)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditAuthorID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAuthorID.setGeometry(QtCore.QRect(140, 140, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditAuthorID.setFont(font)
        self.lineEditAuthorID.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.lineEditAuthorID.setText("")
        self.lineEditAuthorID.setObjectName("lineEditAuthorID")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(140, 190, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.lineEditName.setObjectName("lineEditName")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditGender = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditGender.setGeometry(QtCore.QRect(140, 240, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditGender.setFont(font)
        self.lineEditGender.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.lineEditGender.setObjectName("lineEditGender")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditHometown = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditHometown.setGeometry(QtCore.QRect(140, 290, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditHometown.setFont(font)
        self.lineEditHometown.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.lineEditHometown.setObjectName("lineEditHometown")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 290, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditBookCount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditBookCount.setGeometry(QtCore.QRect(140, 340, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditBookCount.setFont(font)
        self.lineEditBookCount.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.lineEditBookCount.setObjectName("lineEditBookCount")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 340, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEditBooks = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditBooks.setGeometry(QtCore.QRect(140, 389, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditBooks.setFont(font)
        self.lineEditBooks.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.lineEditBooks.setObjectName("lineEditBooks")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 390, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 701, 651))
        self.label_8.setStyleSheet("QLineEdit {\n"
"    background-color: #FFF8DC; /* Màu nền vàng nhạt phù hợp với giao diện */\n"
"    color: black; /* Màu chữ đen để dễ đọc */\n"
"    border-radius: 5px; /* Bo tròn góc nhẹ để đẹp hơn */\n"
"    padding: 5px 10px;\n"
"    font-size: 12px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4B0082; /* Viền xanh đậm giống trong ảnh */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #FAEBD7; /* Màu vàng kem khi hover */\n"
"    border: 2px solid #8A2BE2; /* Viền tím xanh để nổi bật */\n"
"}\n"
"\n"
"/* Khi focus vào (nhấn để nhập) */\n"
"QLineEdit:focus {\n"
"    background-color: #FFD700; /* Màu vàng sáng hơn khi nhập */\n"
"    border: 2px solid #6A5ACD; /* Viền xanh tím */\n"
"}")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pc_background2.jpg"))
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8.raise_()
        self.label_2.raise_()
        self.lineEditAuthorID.raise_()
        self.lineEditName.raise_()
        self.label_3.raise_()
        self.lineEditGender.raise_()
        self.label_4.raise_()
        self.lineEditHometown.raise_()
        self.label_5.raise_()
        self.lineEditBookCount.raise_()
        self.label_6.raise_()
        self.lineEditBooks.raise_()
        self.label_7.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Author ID:"))
        self.label_3.setText(_translate("MainWindow", "Author Name:"))
        self.label_4.setText(_translate("MainWindow", "Gender:"))
        self.label_5.setText(_translate("MainWindow", "Hometown:"))
        self.label_6.setText(_translate("MainWindow", "Book Count:"))
        self.label_7.setText(_translate("MainWindow", "Books:"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">AUTHOR DETAILS</span></p></body></html>"))
