# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 638)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 791, 641))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_login.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 30, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 18pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"\n"
"border-line: rgb(255, 170, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 40, 41, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_person.webp"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(60, 130, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    background-color: #ECF8E5; /* Màu nền xanh nhạt hài hòa với giao diện */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #5C8D55; /* Viền xanh lá đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #DAF0D9; /* Xanh nhạt hơn khi hover */\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào (nhập dữ liệu) */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh lá sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditUserName.setText("")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(60, 200, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    background-color: #ECF8E5; /* Màu nền xanh nhạt hài hòa với giao diện */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #5C8D55; /* Viền xanh lá đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #DAF0D9; /* Xanh nhạt hơn khi hover */\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào (nhập dữ liệu) */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh lá sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(60, 260, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("QPushButton {\n"
"    background-color: #2E7D32; /* Màu xanh đậm của các nút */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1B5E20; /* Viền xanh đậm hơn */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QPushButton:hover {\n"
"    background-color: #388E3C; /* Xanh lá sáng hơn khi hover */\n"
"    border: 2px solid #1B5E20;\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá đậm hơn khi nhấn */\n"
"    border: 2px solid #0D3C14;\n"
"}\n"
"")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 340, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButtonRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(210, 330, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setStyleSheet("QPushButton {\n"
"    background-color: #2E7D32; /* Màu xanh đậm của các nút */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1B5E20; /* Viền xanh đậm hơn */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QPushButton:hover {\n"
"    background-color: #388E3C; /* Xanh lá sáng hơn khi hover */\n"
"    border: 2px solid #1B5E20;\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá đậm hơn khi nhấn */\n"
"    border: 2px solid #0D3C14;\n"
"}\n"
"")
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 180, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 110, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButtonChangePassword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonChangePassword.setGeometry(QtCore.QRect(210, 390, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonChangePassword.setFont(font)
        self.pushButtonChangePassword.setStyleSheet("QPushButton {\n"
"    background-color: #2E7D32; /* Màu xanh đậm của các nút */\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1B5E20; /* Viền xanh đậm hơn */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QPushButton:hover {\n"
"    background-color: #388E3C; /* Xanh lá sáng hơn khi hover */\n"
"    border: 2px solid #1B5E20;\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá đậm hơn khi nhấn */\n"
"    border: 2px solid #0D3C14;\n"
"}\n"
"")
        self.pushButtonChangePassword.setObjectName("pushButtonChangePassword")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 400, 191, 31))
        self.label_7.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login Window"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">WELCOME TO </span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#ffff00;\">LibMas\'s LIBRARY SYSTEM</span></p><p align=\"center\"><span style=\" font-size:14pt; color:#ffff00;\"><br/></span></p></body></html>"))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Enter user name"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Sign In"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">You are new?</span></p></body></html>"))
        self.pushButtonRegister.setText(_translate("MainWindow", "Sign up now"))
        self.label_5.setText(_translate("MainWindow", "PASSWORD"))
        self.label_6.setText(_translate("MainWindow", "USERNAME"))
        self.pushButtonChangePassword.setText(_translate("MainWindow", "Change password"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">You forgot your password?</span></p><p><span style=\" font-size:11pt; font-weight:600;\"><br/></span></p></body></html>"))
