# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\ManagementWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 657)
        MainWindow.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777154))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButtonUpdateReader = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButtonUpdateReader.setGeometry(QtCore.QRect(240, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdateReader.setFont(font)
        self.pushButtonUpdateReader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonUpdateReader.setIcon(icon)
        self.pushButtonUpdateReader.setObjectName("pushButtonUpdateReader")
        self.pushButtonAddReader = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButtonAddReader.setGeometry(QtCore.QRect(100, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddReader.setFont(font)
        self.pushButtonAddReader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_add.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAddReader.setIcon(icon1)
        self.pushButtonAddReader.setObjectName("pushButtonAddReader")
        self.pushButtonShowAllReader = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButtonShowAllReader.setGeometry(QtCore.QRect(520, 260, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShowAllReader.setFont(font)
        self.pushButtonShowAllReader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_showall.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonShowAllReader.setIcon(icon2)
        self.pushButtonShowAllReader.setObjectName("pushButtonShowAllReader")
        self.pushButtonDeleteReader = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButtonDeleteReader.setGeometry(QtCore.QRect(380, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteReader.setFont(font)
        self.pushButtonDeleteReader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_delete.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDeleteReader.setIcon(icon3)
        self.pushButtonDeleteReader.setObjectName("pushButtonDeleteReader")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 310, 871, 281))
        self.groupBox_3.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidgetReader = QtWidgets.QTableWidget(parent=self.groupBox_3)
        self.tableWidgetReader.setStyleSheet("background-color: #D6EFD8")
        self.tableWidgetReader.setObjectName("tableWidgetReader")
        self.tableWidgetReader.setColumnCount(6)
        self.tableWidgetReader.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReader.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReader.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReader.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReader.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReader.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReader.setHorizontalHeaderItem(5, item)
        self.tableWidgetReader.horizontalHeader().setDefaultSectionSize(138)
        self.verticalLayout_5.addWidget(self.tableWidgetReader)
        self.label_13 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 871, 601))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 70, 871, 171))
        self.groupBox_5.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButtonSearchReader = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButtonSearchReader.setGeometry(QtCore.QRect(690, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearchReader.setFont(font)
        self.pushButtonSearchReader.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_search.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearchReader.setIcon(icon4)
        self.pushButtonSearchReader.setObjectName("pushButtonSearchReader")
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.label_24.setObjectName("label_24")
        self.lineEditReaderIDReader = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditReaderIDReader.setGeometry(QtCore.QRect(90, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditReaderIDReader.setFont(font)
        self.lineEditReaderIDReader.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditReaderIDReader.setObjectName("lineEditReaderIDReader")
        self.dateEditDateReader = QtWidgets.QDateEdit(parent=self.groupBox_5)
        self.dateEditDateReader.setGeometry(QtCore.QRect(420, 21, 181, 31))
        self.dateEditDateReader.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.dateEditDateReader.setObjectName("dateEditDateReader")
        self.label_26 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.label_26.setObjectName("label_26")
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(330, 30, 81, 21))
        self.label_23.setObjectName("label_23")
        self.lineEditGenderReader = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditGenderReader.setGeometry(QtCore.QRect(90, 120, 181, 31))
        self.lineEditGenderReader.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditGenderReader.setObjectName("lineEditGenderReader")
        self.label_27 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(330, 80, 81, 21))
        self.label_27.setObjectName("label_27")
        self.lineEditReaderNameReader = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditReaderNameReader.setGeometry(QtCore.QRect(90, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditReaderNameReader.setFont(font)
        self.lineEditReaderNameReader.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditReaderNameReader.setObjectName("lineEditReaderNameReader")
        self.lineEditPhoneReader = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditPhoneReader.setGeometry(QtCore.QRect(420, 70, 181, 31))
        self.lineEditPhoneReader.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditPhoneReader.setObjectName("lineEditPhoneReader")
        self.lineEditSearchReader = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditSearchReader.setGeometry(QtCore.QRect(650, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSearchReader.setFont(font)
        self.lineEditSearchReader.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditSearchReader.setObjectName("lineEditSearchReader")
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(700, 20, 91, 21))
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(330, 130, 71, 21))
        self.label_25.setObjectName("label_25")
        self.lineEditAddressReader = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.lineEditAddressReader.setGeometry(QtCore.QRect(420, 120, 181, 31))
        self.lineEditAddressReader.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditAddressReader.setObjectName("lineEditAddressReader")
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(250, 10, 401, 51))
        self.label_14.setStyleSheet("background-color: #ecf8e5;\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 10px;\n"
"        padding: 5px 15px;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #508D4E;")
        self.label_14.setObjectName("label_14")
        self.label_13.raise_()
        self.pushButtonUpdateReader.raise_()
        self.pushButtonAddReader.raise_()
        self.pushButtonShowAllReader.raise_()
        self.pushButtonDeleteReader.raise_()
        self.groupBox_3.raise_()
        self.groupBox_5.raise_()
        self.label_14.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButtonAddBook = QtWidgets.QPushButton(parent=self.tab)
        self.pushButtonAddBook.setGeometry(QtCore.QRect(110, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddBook.setFont(font)
        self.pushButtonAddBook.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_update.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAddBook.setIcon(icon5)
        self.pushButtonAddBook.setObjectName("pushButtonAddBook")
        self.pushButtonUpdateBook = QtWidgets.QPushButton(parent=self.tab)
        self.pushButtonUpdateBook.setGeometry(QtCore.QRect(260, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdateBook.setFont(font)
        self.pushButtonUpdateBook.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonUpdateBook.setIcon(icon)
        self.pushButtonUpdateBook.setObjectName("pushButtonUpdateBook")
        self.pushButtonDeleteBook = QtWidgets.QPushButton(parent=self.tab)
        self.pushButtonDeleteBook.setGeometry(QtCore.QRect(410, 290, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteBook.setFont(font)
        self.pushButtonDeleteBook.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonDeleteBook.setIcon(icon3)
        self.pushButtonDeleteBook.setObjectName("pushButtonDeleteBook")
        self.pushButtonShowAllBook = QtWidgets.QPushButton(parent=self.tab)
        self.pushButtonShowAllBook.setGeometry(QtCore.QRect(560, 290, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShowAllBook.setFont(font)
        self.pushButtonShowAllBook.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonShowAllBook.setIcon(icon2)
        self.pushButtonShowAllBook.setObjectName("pushButtonShowAllBook")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 340, 871, 251))
        self.groupBox.setStyleSheet("background-color: #D6EFD8")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidgetBook = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidgetBook.setStyleSheet("background-color: #D6EFD8")
        self.tableWidgetBook.setObjectName("tableWidgetBook")
        self.tableWidgetBook.setColumnCount(8)
        self.tableWidgetBook.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(236, 248, 229))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.tableWidgetBook.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBook.setHorizontalHeaderItem(7, item)
        self.tableWidgetBook.horizontalHeader().setDefaultSectionSize(103)
        self.verticalLayout_2.addWidget(self.tableWidgetBook)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 60, 871, 221))
        self.groupBox_2.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButtonSearchBook = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonSearchBook.setGeometry(QtCore.QRect(690, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearchBook.setFont(font)
        self.pushButtonSearchBook.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonSearchBook.setIcon(icon4)
        self.pushButtonSearchBook.setObjectName("pushButtonSearchBook")
        self.dateEditPublishDateBook = QtWidgets.QDateEdit(parent=self.groupBox_2)
        self.dateEditPublishDateBook.setGeometry(QtCore.QRect(430, 30, 181, 31))
        self.dateEditPublishDateBook.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.dateEditPublishDateBook.setObjectName("dateEditPublishDateBook")
        self.lineEditPublisher = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPublisher.setGeometry(QtCore.QRect(100, 180, 181, 31))
        self.lineEditPublisher.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditPublisher.setObjectName("lineEditPublisher")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 81, 21))
        self.label_5.setStyleSheet("background-color: #D6EFD8")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(340, 130, 81, 21))
        self.label_7.setStyleSheet("background-color: #D6EFD8")
        self.label_7.setObjectName("label_7")
        self.lineEditAuthorBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditAuthorBook.setGeometry(QtCore.QRect(430, 180, 181, 31))
        self.lineEditAuthorBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditAuthorBook.setObjectName("lineEditAuthorBook")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 71, 21))
        self.label_4.setStyleSheet("background-color: #D6EFD8")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 81, 21))
        self.label_2.setStyleSheet("background-color: #D6EFD8")
        self.label_2.setObjectName("label_2")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(700, 50, 91, 21))
        self.label_9.setStyleSheet("background-color: #D6EFD8")
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(340, 80, 81, 21))
        self.label_6.setStyleSheet("background-color: #D6EFD8")
        self.label_6.setObjectName("label_6")
        self.lineEditQuantityBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditQuantityBook.setGeometry(QtCore.QRect(430, 80, 181, 31))
        self.lineEditQuantityBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditQuantityBook.setObjectName("lineEditQuantityBook")
        self.lineEditSearchBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditSearchBook.setGeometry(QtCore.QRect(650, 80, 191, 31))
        self.lineEditSearchBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditSearchBook.setObjectName("lineEditSearchBook")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 81, 21))
        self.label_3.setStyleSheet("background-color: #D6EFD8")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #D6EFD8")
        self.label.setObjectName("label")
        self.lineEditTypeBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditTypeBook.setGeometry(QtCore.QRect(100, 130, 181, 31))
        self.lineEditTypeBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditTypeBook.setObjectName("lineEditTypeBook")
        self.lineEditBookNameBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditBookNameBook.setGeometry(QtCore.QRect(100, 80, 181, 31))
        self.lineEditBookNameBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditBookNameBook.setObjectName("lineEditBookNameBook")
        self.lineEditPriceBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPriceBook.setGeometry(QtCore.QRect(430, 130, 181, 31))
        self.lineEditPriceBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditPriceBook.setObjectName("lineEditPriceBook")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(340, 180, 81, 21))
        self.label_8.setStyleSheet("background-color: #D6EFD8")
        self.label_8.setObjectName("label_8")
        self.lineEditBookIDBook = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditBookIDBook.setGeometry(QtCore.QRect(100, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditBookIDBook.setFont(font)
        self.lineEditBookIDBook.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.lineEditBookIDBook.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditBookIDBook.setObjectName("lineEditBookIDBook")
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 881, 611))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.tab)
        self.label_11.setGeometry(QtCore.QRect(290, 0, 321, 51))
        self.label_11.setStyleSheet("background-color: #ecf8e5;\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 10px;\n"
"        padding: 5px 15px;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #508D4E;")
        self.label_11.setObjectName("label_11")
        self.label_10.raise_()
        self.pushButtonAddBook.raise_()
        self.pushButtonUpdateBook.raise_()
        self.pushButtonDeleteBook.raise_()
        self.pushButtonShowAllBook.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.label_11.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButtonAddAuthor = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButtonAddAuthor.setGeometry(QtCore.QRect(150, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddAuthor.setFont(font)
        self.pushButtonAddAuthor.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonAddAuthor.setIcon(icon1)
        self.pushButtonAddAuthor.setObjectName("pushButtonAddAuthor")
        self.pushButtonShowAllAuthor = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButtonShowAllAuthor.setGeometry(QtCore.QRect(570, 300, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShowAllAuthor.setFont(font)
        self.pushButtonShowAllAuthor.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonShowAllAuthor.setIcon(icon2)
        self.pushButtonShowAllAuthor.setObjectName("pushButtonShowAllAuthor")
        self.pushButtonDeleteAuthor = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButtonDeleteAuthor.setGeometry(QtCore.QRect(430, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteAuthor.setFont(font)
        self.pushButtonDeleteAuthor.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonDeleteAuthor.setIcon(icon3)
        self.pushButtonDeleteAuthor.setObjectName("pushButtonDeleteAuthor")
        self.pushButtonUpdateAuthor = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButtonUpdateAuthor.setGeometry(QtCore.QRect(290, 300, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdateAuthor.setFont(font)
        self.pushButtonUpdateAuthor.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonUpdateAuthor.setIcon(icon)
        self.pushButtonUpdateAuthor.setObjectName("pushButtonUpdateAuthor")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 350, 871, 241))
        self.groupBox_4.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidgetAuthor = QtWidgets.QTableWidget(parent=self.groupBox_4)
        self.tableWidgetAuthor.setStyleSheet("background-color: #D6EFD8\n"
"")
        self.tableWidgetAuthor.setObjectName("tableWidgetAuthor")
        self.tableWidgetAuthor.setColumnCount(4)
        self.tableWidgetAuthor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAuthor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAuthor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAuthor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAuthor.setHorizontalHeaderItem(3, item)
        self.tableWidgetAuthor.horizontalHeader().setDefaultSectionSize(207)
        self.verticalLayout_7.addWidget(self.tableWidgetAuthor)
        self.label_12 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 881, 591))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 80, 881, 211))
        self.groupBox_6.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButtonSearchAuthor = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButtonSearchAuthor.setGeometry(QtCore.QRect(610, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearchAuthor.setFont(font)
        self.pushButtonSearchAuthor.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonSearchAuthor.setIcon(icon4)
        self.pushButtonSearchAuthor.setObjectName("pushButtonSearchAuthor")
        self.label_30 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_30.setGeometry(QtCore.QRect(90, 20, 91, 21))
        self.label_30.setObjectName("label_30")
        self.label_29 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_29.setGeometry(QtCore.QRect(90, 70, 81, 21))
        self.label_29.setObjectName("label_29")
        self.lineEditAuthorIDAuthor = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditAuthorIDAuthor.setGeometry(QtCore.QRect(170, 20, 181, 31))
        self.lineEditAuthorIDAuthor.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditAuthorIDAuthor.setObjectName("lineEditAuthorIDAuthor")
        self.lineEditHometownAuthor = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditHometownAuthor.setGeometry(QtCore.QRect(170, 170, 181, 31))
        self.lineEditHometownAuthor.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditHometownAuthor.setObjectName("lineEditHometownAuthor")
        self.lineEditAuthorNameAuthor = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditAuthorNameAuthor.setGeometry(QtCore.QRect(170, 70, 181, 31))
        self.lineEditAuthorNameAuthor.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditAuthorNameAuthor.setObjectName("lineEditAuthorNameAuthor")
        self.label_33 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_33.setGeometry(QtCore.QRect(90, 170, 71, 21))
        self.label_33.setObjectName("label_33")
        self.lineEditSearchAuthor = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditSearchAuthor.setGeometry(QtCore.QRect(550, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditSearchAuthor.setFont(font)
        self.lineEditSearchAuthor.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditSearchAuthor.setObjectName("lineEditSearchAuthor")
        self.label_28 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_28.setGeometry(QtCore.QRect(90, 120, 91, 21))
        self.label_28.setObjectName("label_28")
        self.label_32 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_32.setGeometry(QtCore.QRect(610, 30, 91, 21))
        self.label_32.setObjectName("label_32")
        self.lineEditGenderAuthor = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditGenderAuthor.setGeometry(QtCore.QRect(170, 120, 181, 31))
        self.lineEditGenderAuthor.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditGenderAuthor.setObjectName("lineEditGenderAuthor")
        self.label_15 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(250, 20, 401, 51))
        self.label_15.setStyleSheet("background-color: #ecf8e5;\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 10px;\n"
"        padding: 5px 15px;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #508D4E;")
        self.label_15.setObjectName("label_15")
        self.label_12.raise_()
        self.pushButtonAddAuthor.raise_()
        self.pushButtonShowAllAuthor.raise_()
        self.pushButtonDeleteAuthor.raise_()
        self.pushButtonUpdateAuthor.raise_()
        self.groupBox_4.raise_()
        self.groupBox_6.raise_()
        self.label_15.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButtonAddOrder = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButtonAddOrder.setGeometry(QtCore.QRect(130, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAddOrder.setFont(font)
        self.pushButtonAddOrder.setStyleSheet("background-color: rgb(163, 222, 164);\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 3px;\n"
"        padding: 5px 15px;\n"
"        font-size: 13px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #1A5319;\n"
"")
        self.pushButtonAddOrder.setIcon(icon1)
        self.pushButtonAddOrder.setObjectName("pushButtonAddOrder")
        self.pushButtonUpdateOrder = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButtonUpdateOrder.setGeometry(QtCore.QRect(330, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonUpdateOrder.setFont(font)
        self.pushButtonUpdateOrder.setStyleSheet("background-color: rgb(163, 222, 164);\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 3px;\n"
"        padding: 5px 15px;\n"
"        font-size: 13px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #1A5319;")
        self.pushButtonUpdateOrder.setIcon(icon)
        self.pushButtonUpdateOrder.setObjectName("pushButtonUpdateOrder")
        self.groupBox_11 = QtWidgets.QGroupBox(parent=self.tab_4)
        self.groupBox_11.setGeometry(QtCore.QRect(0, 350, 871, 241))
        self.groupBox_11.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableWidgetBorrowAndReturn = QtWidgets.QTableWidget(parent=self.groupBox_11)
        self.tableWidgetBorrowAndReturn.setStyleSheet("background-color: #D6EFD8")
        self.tableWidgetBorrowAndReturn.setLineWidth(1)
        self.tableWidgetBorrowAndReturn.setObjectName("tableWidgetBorrowAndReturn")
        self.tableWidgetBorrowAndReturn.setColumnCount(7)
        self.tableWidgetBorrowAndReturn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBorrowAndReturn.setHorizontalHeaderItem(6, item)
        self.tableWidgetBorrowAndReturn.horizontalHeader().setDefaultSectionSize(117)
        self.verticalLayout_14.addWidget(self.tableWidgetBorrowAndReturn)
        self.pushButtonDeleteOrder = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButtonDeleteOrder.setGeometry(QtCore.QRect(530, 300, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDeleteOrder.setFont(font)
        self.pushButtonDeleteOrder.setStyleSheet("background-color: rgb(163, 222, 164);\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 3px;\n"
"        padding: 5px 15px;\n"
"        font-size: 13px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #1A5319;")
        self.pushButtonDeleteOrder.setIcon(icon3)
        self.pushButtonDeleteOrder.setObjectName("pushButtonDeleteOrder")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 110, 871, 171))
        self.groupBox_7.setStyleSheet("background-color: #D6EFD8")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.dateEditDateBorrowing = QtWidgets.QDateEdit(parent=self.groupBox_7)
        self.dateEditDateBorrowing.setGeometry(QtCore.QRect(580, 30, 181, 31))
        self.dateEditDateBorrowing.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.dateEditDateBorrowing.setObjectName("dateEditDateBorrowing")
        self.label_56 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_56.setGeometry(QtCore.QRect(460, 30, 111, 21))
        self.label_56.setObjectName("label_56")
        self.dateEditDateReturning = QtWidgets.QDateEdit(parent=self.groupBox_7)
        self.dateEditDateReturning.setGeometry(QtCore.QRect(580, 80, 181, 31))
        self.dateEditDateReturning.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.dateEditDateReturning.setObjectName("dateEditDateReturning")
        self.label_55 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_55.setGeometry(QtCore.QRect(90, 130, 81, 21))
        self.label_55.setObjectName("label_55")
        self.label_57 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_57.setGeometry(QtCore.QRect(460, 80, 111, 21))
        self.label_57.setObjectName("label_57")
        self.comboBoxStatus = QtWidgets.QComboBox(parent=self.groupBox_7)
        self.comboBoxStatus.setGeometry(QtCore.QRect(580, 130, 181, 31))
        self.comboBoxStatus.setStyleSheet("QComboBox {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QComboBox:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào (click để mở dropdown) */\n"
"QComboBox:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"\n"
"")
        self.comboBoxStatus.setObjectName("comboBoxStatus")
        self.comboBoxStatus.addItem("")
        self.comboBoxStatus.addItem("")
        self.lineEditReaderIDBR = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.lineEditReaderIDBR.setGeometry(QtCore.QRect(170, 30, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineEditReaderIDBR.setFont(font)
        self.lineEditReaderIDBR.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditReaderIDBR.setObjectName("lineEditReaderIDBR")
        self.label_58 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_58.setGeometry(QtCore.QRect(460, 130, 111, 21))
        self.label_58.setObjectName("label_58")
        self.label_52 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_52.setGeometry(QtCore.QRect(90, 80, 81, 21))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(parent=self.groupBox_7)
        self.label_53.setGeometry(QtCore.QRect(90, 30, 71, 21))
        self.label_53.setObjectName("label_53")
        self.lineEditBookIDBR = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.lineEditBookIDBR.setGeometry(QtCore.QRect(170, 80, 181, 31))
        self.lineEditBookIDBR.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditBookIDBR.setObjectName("lineEditBookIDBR")
        self.lineEditQuantityBR = QtWidgets.QLineEdit(parent=self.groupBox_7)
        self.lineEditQuantityBR.setGeometry(QtCore.QRect(170, 120, 181, 31))
        self.lineEditQuantityBR.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"")
        self.lineEditQuantityBR.setObjectName("lineEditQuantityBR")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(110, 30, 661, 51))
        self.label_16.setStyleSheet("background-color: #ecf8e5;\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 10px;\n"
"        padding: 5px 15px;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #508D4E;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 871, 601))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_17.raise_()
        self.pushButtonAddOrder.raise_()
        self.pushButtonUpdateOrder.raise_()
        self.groupBox_11.raise_()
        self.pushButtonDeleteOrder.raise_()
        self.groupBox_7.raise_()
        self.label_16.raise_()
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 18))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuExport_Excel = QtWidgets.QMenu(parent=self.menuHelp)
        self.menuExport_Excel.setObjectName("menuExport_Excel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLog_Out = QtGui.QAction(parent=MainWindow)
        self.actionLog_Out.setObjectName("actionLog_Out")
        self.actionExport_Reader_Data = QtGui.QAction(parent=MainWindow)
        self.actionExport_Reader_Data.setObjectName("actionExport_Reader_Data")
        self.actionExport_Book_Data = QtGui.QAction(parent=MainWindow)
        self.actionExport_Book_Data.setObjectName("actionExport_Book_Data")
        self.actionExport_Author_Data = QtGui.QAction(parent=MainWindow)
        self.actionExport_Author_Data.setObjectName("actionExport_Author_Data")
        self.actionExport_Order_Data = QtGui.QAction(parent=MainWindow)
        self.actionExport_Order_Data.setObjectName("actionExport_Order_Data")
        self.actionExport_All = QtGui.QAction(parent=MainWindow)
        self.actionExport_All.setObjectName("actionExport_All")
        self.menuExport_Excel.addAction(self.actionExport_Reader_Data)
        self.menuExport_Excel.addAction(self.actionExport_Book_Data)
        self.menuExport_Excel.addAction(self.actionExport_Author_Data)
        self.menuExport_Excel.addAction(self.actionExport_Order_Data)
        self.menuExport_Excel.addSeparator()
        self.menuExport_Excel.addAction(self.actionExport_All)
        self.menuHelp.addAction(self.actionLog_Out)
        self.menuHelp.addAction(self.menuExport_Excel.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonUpdateReader.setText(_translate("MainWindow", "Update"))
        self.pushButtonAddReader.setText(_translate("MainWindow", "Add"))
        self.pushButtonShowAllReader.setText(_translate("MainWindow", "Show all"))
        self.pushButtonDeleteReader.setText(_translate("MainWindow", "Delete"))
        item = self.tableWidgetReader.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Reader ID"))
        item = self.tableWidgetReader.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidgetReader.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidgetReader.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "B.O.D"))
        item = self.tableWidgetReader.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidgetReader.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Address"))
        self.pushButtonSearchReader.setText(_translate("MainWindow", "Search"))
        self.label_24.setText(_translate("MainWindow", "Reader ID:"))
        self.label_26.setText(_translate("MainWindow", "Full Name:"))
        self.label_23.setText(_translate("MainWindow", "B.O.D:"))
        self.label_27.setText(_translate("MainWindow", "Phone:"))
        self.label_22.setText(_translate("MainWindow", "SEARCHING"))
        self.label_25.setText(_translate("MainWindow", "Address:"))
        self.label_21.setText(_translate("MainWindow", "Gender:"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">READER MANAGEMENT</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Reader Management"))
        self.pushButtonAddBook.setText(_translate("MainWindow", "Add"))
        self.pushButtonUpdateBook.setText(_translate("MainWindow", "Update"))
        self.pushButtonDeleteBook.setText(_translate("MainWindow", "Delete"))
        self.pushButtonShowAllBook.setText(_translate("MainWindow", "Show all"))
        item = self.tableWidgetBook.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book ID"))
        item = self.tableWidgetBook.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidgetBook.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Type"))
        item = self.tableWidgetBook.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Publish Date"))
        item = self.tableWidgetBook.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Publisher"))
        item = self.tableWidgetBook.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidgetBook.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidgetBook.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Author"))
        self.pushButtonSearchBook.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "Publish Date:"))
        self.label_7.setText(_translate("MainWindow", "Price:"))
        self.label_4.setText(_translate("MainWindow", "Publisher:"))
        self.label_2.setText(_translate("MainWindow", "Book Name:"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">SEARCHING</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Quantity:"))
        self.label_3.setText(_translate("MainWindow", "Book Type:"))
        self.label.setText(_translate("MainWindow", "Book ID:"))
        self.label_8.setText(_translate("MainWindow", "Author:"))
        self.lineEditBookIDBook.setText(_translate("MainWindow", "234111"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">BOOK MANAGEMENT </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Book Management"))
        self.pushButtonAddAuthor.setText(_translate("MainWindow", "Add"))
        self.pushButtonShowAllAuthor.setText(_translate("MainWindow", "Show all"))
        self.pushButtonDeleteAuthor.setText(_translate("MainWindow", "Delete"))
        self.pushButtonUpdateAuthor.setText(_translate("MainWindow", "Update"))
        item = self.tableWidgetAuthor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Author ID"))
        item = self.tableWidgetAuthor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Full Name"))
        item = self.tableWidgetAuthor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.tableWidgetAuthor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hometown"))
        self.pushButtonSearchAuthor.setText(_translate("MainWindow", "Search"))
        self.label_30.setText(_translate("MainWindow", "Author ID:"))
        self.label_29.setText(_translate("MainWindow", "Full Name:"))
        self.label_33.setText(_translate("MainWindow", "Hometown:"))
        self.label_28.setText(_translate("MainWindow", "Gender:"))
        self.label_32.setText(_translate("MainWindow", "SEARCHING"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">AUTHOR MANAGEMENT</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Author Management"))
        self.pushButtonAddOrder.setText(_translate("MainWindow", "Add"))
        self.pushButtonUpdateOrder.setText(_translate("MainWindow", "Update"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order ID"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Reader ID"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book ID"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Borrowing Date"))
        item = self.tableWidgetBorrowAndReturn.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Returning Date"))
        self.pushButtonDeleteOrder.setText(_translate("MainWindow", "Delete"))
        self.label_56.setText(_translate("MainWindow", "Borrowing Date:"))
        self.label_55.setText(_translate("MainWindow", "Quantity:"))
        self.label_57.setText(_translate("MainWindow", "Returning Date:"))
        self.comboBoxStatus.setItemText(0, _translate("MainWindow", "Not Returned"))
        self.comboBoxStatus.setItemText(1, _translate("MainWindow", "Returned"))
        self.label_58.setText(_translate("MainWindow", "Status:"))
        self.label_52.setText(_translate("MainWindow", "Book ID:"))
        self.label_53.setText(_translate("MainWindow", "Reader ID:"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">BORROWING AND RETURNING MANAGEMENT</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Borrowing and Returning Management"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuExport_Excel.setTitle(_translate("MainWindow", "Export Excel"))
        self.actionLog_Out.setText(_translate("MainWindow", "Log Out"))
        self.actionExport_Reader_Data.setText(_translate("MainWindow", "Export Reader Data"))
        self.actionExport_Book_Data.setText(_translate("MainWindow", "Export Book Data"))
        self.actionExport_Author_Data.setText(_translate("MainWindow", "Export Author Data"))
        self.actionExport_Order_Data.setText(_translate("MainWindow", "Export Order Data"))
        self.actionExport_All.setText(_translate("MainWindow", "Export All"))
