# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\OrderDetailWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 447)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #ecf8e5;\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 10px;\n"
"        padding: 5px 15px;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #508D4E;\n"
"font: 75 20pt \"Times New Roman\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditOrderID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditOrderID.setGeometry(QtCore.QRect(160, 90, 291, 31))
        self.lineEditOrderID.setStyleSheet("QLineEdit {\n"
"    background-color: #EFF8E5; /* Màu nền xanh lá nhạt */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #E0F2D8; /* Xanh lá nhạt hơn khi hover */\n"
"    border: 2px solid #3B6D33; /* Viền đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditOrderID.setText("")
        self.lineEditOrderID.setObjectName("lineEditOrderID")
        self.lineEditReaderID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditReaderID.setGeometry(QtCore.QRect(160, 130, 291, 31))
        self.lineEditReaderID.setStyleSheet("QLineEdit {\n"
"    background-color: #EFF8E5; /* Màu nền xanh lá nhạt */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #E0F2D8; /* Xanh lá nhạt hơn khi hover */\n"
"    border: 2px solid #3B6D33; /* Viền đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditReaderID.setObjectName("lineEditReaderID")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditBookID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditBookID.setGeometry(QtCore.QRect(160, 170, 291, 31))
        self.lineEditBookID.setStyleSheet("QLineEdit {\n"
"    background-color: #EFF8E5; /* Màu nền xanh lá nhạt */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #E0F2D8; /* Xanh lá nhạt hơn khi hover */\n"
"    border: 2px solid #3B6D33; /* Viền đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditBookID.setObjectName("lineEditBookID")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 170, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditQuantity.setGeometry(QtCore.QRect(160, 210, 291, 31))
        self.lineEditQuantity.setStyleSheet("QLineEdit {\n"
"    background-color: #EFF8E5; /* Màu nền xanh lá nhạt */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #E0F2D8; /* Xanh lá nhạt hơn khi hover */\n"
"    border: 2px solid #3B6D33; /* Viền đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditStatus = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditStatus.setGeometry(QtCore.QRect(160, 250, 291, 31))
        self.lineEditStatus.setStyleSheet("QLineEdit {\n"
"    background-color: #EFF8E5; /* Màu nền xanh lá nhạt */\n"
"    color: #2E4E1E; /* Màu chữ xanh đậm */\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43; /* Viền xanh đậm */\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QLineEdit:hover {\n"
"    background-color: #E0F2D8; /* Xanh lá nhạt hơn khi hover */\n"
"    border: 2px solid #3B6D33; /* Viền đậm hơn */\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh sáng hơn khi nhập */\n"
"    border: 2px solid #2E4E1E; /* Viền xanh đậm */\n"
"}\n"
"")
        self.lineEditStatus.setObjectName("lineEditStatus")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 250, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 290, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.dateEditBorrow = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditBorrow.setGeometry(QtCore.QRect(160, 290, 291, 31))
        self.dateEditBorrow.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #EFF8E5; /* Màu nền giống QLineEdit */\n"
"    color: #2E4E1E;\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F2D8;\n"
"    border: 2px solid #3B6D33;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #C5E1A5;\n"
"    border: 2px solid #2E4E1E;\n"
"}\n"
"\n"
"")
        self.dateEditBorrow.setObjectName("dateEditBorrow")
        self.dateEditReturn = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditReturn.setGeometry(QtCore.QRect(160, 330, 291, 31))
        self.dateEditReturn.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #EFF8E5; /* Màu nền giống QLineEdit */\n"
"    color: #2E4E1E;\n"
"    border-radius: 5px;\n"
"    padding: 6px 12px;\n"
"    font-size: 10px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4A7D43;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F2D8;\n"
"    border: 2px solid #3B6D33;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #C5E1A5;\n"
"    border: 2px solid #2E4E1E;\n"
"}\n"
"\n"
"")
        self.dateEditReturn.setObjectName("dateEditReturn")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 330, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 531, 411))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_9.setObjectName("label_9")
        self.label_9.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEditOrderID.raise_()
        self.lineEditReaderID.raise_()
        self.label_3.raise_()
        self.lineEditBookID.raise_()
        self.label_4.raise_()
        self.lineEditQuantity.raise_()
        self.label_5.raise_()
        self.lineEditStatus.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.dateEditBorrow.raise_()
        self.dateEditReturn.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ORDER DETAIL</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Order ID:"))
        self.label_3.setText(_translate("MainWindow", "Reader ID:"))
        self.label_4.setText(_translate("MainWindow", "Book ID:"))
        self.label_5.setText(_translate("MainWindow", "Quantity:"))
        self.label_6.setText(_translate("MainWindow", "Status:"))
        self.label_7.setText(_translate("MainWindow", "Borrowing Date:"))
        self.label_8.setText(_translate("MainWindow", "Returning Date:"))
