# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\RegisterWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 661)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -80, 721, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/signup.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #ecf8e5;\n"
"        color: rgb(0, 0, 0);\n"
"        border-radius: 10px;\n"
"        padding: 5px 15px;\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        border: 2px solid #508D4E;\n"
"font: 75 20pt \"Times New Roman\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 91, 91, 31))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(150, 90, 461, 31))
        self.lineEditUserName.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.lineEditUserName.setText("")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(150, 140, 461, 31))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 141, 91, 31))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditFullName.setGeometry(QtCore.QRect(150, 190, 461, 31))
        self.lineEditFullName.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 190, 91, 31))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 280, 91, 31))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.lineEditPhone = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPhone.setGeometry(QtCore.QRect(150, 330, 461, 31))
        self.lineEditPhone.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.lineEditPhone.setObjectName("lineEditPhone")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 330, 91, 31))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_7.setObjectName("label_7")
        self.lineEditAddress = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAddress.setGeometry(QtCore.QRect(150, 380, 461, 31))
        self.lineEditAddress.setStyleSheet("QLineEdit {\n"
"    background-color: #ecf8e5;\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 380, 91, 31))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_8.setObjectName("label_8")
        self.pushButtonSignUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSignUp.setGeometry(QtCore.QRect(230, 500, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSignUp.setFont(font)
        self.pushButtonSignUp.setStyleSheet("QPushButton {\n"
"    background-color: rgb(163, 222, 164); /* Màu nền ban đầu */\n"
"    color: black;\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1A5319;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(140, 200, 140); /* Màu khi trỏ chuột vào */\n"
"    border: 2px solid #136b13;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(100, 181, 100); /* Màu khi bấm vào */\n"
"    border: 2px solid #0D471A;\n"
"}")
        self.pushButtonSignUp.setObjectName("pushButtonSignUp")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 230, 91, 31))
        self.label_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"\n"
"font: 75 11pt \"Times New Roman\";")
        self.label_9.setObjectName("label_9")
        self.dateEditDate = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditDate.setGeometry(QtCore.QRect(150, 280, 461, 31))
        self.dateEditDate.setStyleSheet("QDateTimeEdit {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QDateTimeEdit:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào */\n"
"QDateTimeEdit:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.dateEditDate.setObjectName("dateEditDate")
        self.comboBoxGender = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxGender.setGeometry(QtCore.QRect(150, 240, 461, 31))
        self.comboBoxGender.setStyleSheet("QComboBox {\n"
"    background-color: #ecf8e5; /* Màu nền giống QLineEdit */\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 3px;\n"
"    padding: 5px 15px;\n"
"    font-size: 9px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #508D4E;\n"
"}\n"
"\n"
"/* Khi trỏ chuột vào */\n"
"QComboBox:hover {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}\n"
"\n"
"/* Khi focus vào (click để mở dropdown) */\n"
"QComboBox:focus {\n"
"    background-color: #E0F7FA;\n"
"    border: 2px solid #00897B;\n"
"}")
        self.comboBoxGender.setObjectName("comboBoxGender")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.radioButtonAdmin = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonAdmin.setGeometry(QtCore.QRect(200, 420, 101, 41))
        self.radioButtonAdmin.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #1B5E20;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #388E3C;\n"
"    background-color: #E8F5E9;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #4CAF50;\n"
"    border: 2px solid #2E7D32;\n"
"}\n"
"")
        self.radioButtonAdmin.setObjectName("radioButtonAdmin")
        self.radioButtonUser = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonUser.setGeometry(QtCore.QRect(450, 420, 131, 41))
        self.radioButtonUser.setStyleSheet("QRadioButton {\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: #1B5E20;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 9px;\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border: 2px solid #388E3C;\n"
"    background-color: #E8F5E9;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #4CAF50;\n"
"    border: 2px solid #2E7D32;\n"
"}\n"
"")
        self.radioButtonUser.setObjectName("radioButtonUser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">SIGN UP</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "User Name:"))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.label_5.setText(_translate("MainWindow", "Full Name:"))
        self.label_6.setText(_translate("MainWindow", "Date of birth:"))
        self.label_7.setText(_translate("MainWindow", "Phone"))
        self.label_8.setText(_translate("MainWindow", "Address:"))
        self.pushButtonSignUp.setText(_translate("MainWindow", "Sign Up"))
        self.label_9.setText(_translate("MainWindow", "Gender:"))
        self.comboBoxGender.setItemText(0, _translate("MainWindow", "Male"))
        self.comboBoxGender.setItemText(1, _translate("MainWindow", "Female"))
        self.radioButtonAdmin.setText(_translate("MainWindow", "Admin"))
        self.radioButtonUser.setText(_translate("MainWindow", "User"))
