# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\UserMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1396, 658)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelWelcome = QtWidgets.QLabel(parent=self.groupBox)
        self.labelWelcome.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelWelcome.setFont(font)
        self.labelWelcome.setStyleSheet("color: rgb(0, 170, 0);")
        self.labelWelcome.setText("")
        self.labelWelcome.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.labelWelcome.setObjectName("labelWelcome")
        self.verticalLayout_3.addWidget(self.labelWelcome)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF; /* Nền trắng */\n"
"    color: #1B5E20; /* Chữ xanh lá đậm */\n"
"    border-radius: 5px; /* Bo góc mềm mại hơn */\n"
"    padding: 6px 10px;\n"
"    font-size: 8px;\n"
"    font-weight: bold;\n"
"    border: 2px solid #4CAF50; /* Viền xanh lá vừa phải */\n"
"}\n"
"\n"
"/* Khi hover vào ô nhập */\n"
"QLineEdit:hover {\n"
"    background-color: #E8F5E9; /* Xanh lá nhạt hơn khi hover */\n"
"    border: 2px solid #388E3C; /* Viền xanh lá đậm hơn */\n"
"}\n"
"\n"
"/* Khi ô nhập có focus */\n"
"QLineEdit:focus {\n"
"    background-color: #C5E1A5; /* Màu xanh sáng khi nhập */\n"
"    border: 2px solid #2E7D32; /* Viền xanh lá đậm hơn */\n"
"}\n"
"")
        self.lineEditSearch.setText("")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.verticalLayout_3.addWidget(self.lineEditSearch)
        self.pushButtonSearchBook = QtWidgets.QPushButton(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSearchBook.setFont(font)
        self.pushButtonSearchBook.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Màu xanh lá chủ đạo */\n"
"    color: white;\n"
"    font-size: 8px;\n"
"    font-weight: bold;\n"
"    border-radius: 2px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Khi hover vào nút */\n"
"QPushButton:hover {\n"
"    background-color: #2E7D32; /* Xanh lá đậm hơn */\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá rừng đậm */\n"
"}\n"
"")
        self.pushButtonSearchBook.setObjectName("pushButtonSearchBook")
        self.verticalLayout_3.addWidget(self.pushButtonSearchBook)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 1361, 311))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(-130, -280, 1761, 701))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.tableWidget.raise_()
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 15, 521, 21))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    color: #1B5E20; /* Xanh lá đậm hơn */\n"
"}")
        self.label.setObjectName("label")
        self.pushButtonLogOut_2 = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonLogOut_2.setGeometry(QtCore.QRect(1230, 10, 81, 31))
        self.pushButtonLogOut_2.setStyleSheet("QPushButton {\n"
"       background-color: #4CAF50; /* Màu xanh lá chủ đạo */\n"
"    color: white;\n"
"    font-size: 8px;\n"
"    font-weight: bold;\n"
"    border-radius: 2px;\n"
"    padding: 8px 16px;\n"
"    border: none;}\n"
"\n"
"/* Khi hover vào nút */\n"
"QPushButton:hover {\n"
"    background-color: #2E7D32; /* Xanh lá đậm hơn */\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá rừng đậm */\n"
"}\n"
"")
        self.pushButtonLogOut_2.setObjectName("pushButtonLogOut_2")
        self.labelTotal = QtWidgets.QLabel(parent=self.groupBox_3)
        self.labelTotal.setGeometry(QtCore.QRect(60, 15, 621, 21))
        self.labelTotal.setText("")
        self.labelTotal.setObjectName("labelTotal")
        self.pushButtonOrder = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonOrder.setGeometry(QtCore.QRect(1030, 10, 81, 31))
        self.pushButtonOrder.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Màu xanh lá chủ đạo */\n"
"    color: white;\n"
"    font-size: 8px;\n"
"    font-weight: bold;\n"
"    border-radius: 2px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Khi hover vào nút */\n"
"QPushButton:hover {\n"
"    background-color: #2E7D32; /* Xanh lá đậm hơn */\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá rừng đậm */\n"
"}\n"
"")
        self.pushButtonOrder.setObjectName("pushButtonOrder")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(-130, -191, 1601, 311))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_background.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label.raise_()
        self.pushButtonLogOut_2.raise_()
        self.labelTotal.raise_()
        self.pushButtonOrder.raise_()
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1396, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditSearch.setPlaceholderText(_translate("MainWindow", "Search author or book here:"))
        self.pushButtonSearchBook.setText(_translate("MainWindow", "Search"))
        self.groupBox_2.setTitle(_translate("MainWindow", "List of Books:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Published Date"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Publisher"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Stock"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Borrowing Quantity "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Total:"))
        self.label.setText(_translate("MainWindow", "Total:"))
        self.pushButtonLogOut_2.setText(_translate("MainWindow", "Log Out"))
        self.pushButtonOrder.setText(_translate("MainWindow", "Order"))
