# Form implementation generated from reading ui file 'E:\PYTHON\KĨ THUẬT LẬP TRÌNH - HK2\FinalProject\ui\UserOrderWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 584)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 651, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutOrder = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutOrder.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutOrder.setObjectName("verticalLayoutOrder")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"Century Gothic\";")
        self.label.setObjectName("label")
        self.verticalLayoutOrder.addWidget(self.label)
        self.pushButtonConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonConfirm.setGeometry(QtCore.QRect(270, 380, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonConfirm.setFont(font)
        self.pushButtonConfirm.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50; /* Màu xanh lá chủ đạo */\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 2px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Khi hover vào nút */\n"
"QPushButton:hover {\n"
"    background-color: #2E7D32; /* Xanh lá đậm hơn */\n"
"}\n"
"\n"
"/* Khi bấm vào */\n"
"QPushButton:pressed {\n"
"    background-color: #1B5E20; /* Xanh lá rừng đậm */\n"
"}\n"
"")
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-40, -1, 831, 561))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:\\PYTHON\\KĨ THUẬT LẬP TRÌNH - HK2\\FinalProject\\ui\\../images/pic_register.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.verticalLayoutWidget.raise_()
        self.pushButtonConfirm.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "YOUR ORDER:"))
        self.pushButtonConfirm.setText(_translate("MainWindow", "Confirm Order"))
